name: "Build and Release"
on:
  push:
    tags:
      - "v*"

jobs:
  check_release:
    name: "Check Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Check if tag is valid"
        run: |
          if [[ ! ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag is not valid"
            exit 1
          fi
      - name: "Get release name"
        id: get_release_name
        run: |
          echo "release_name=$(echo "${{ github.ref }}" | sed s%"refs/tags/v"%%)" >> "$GITHUB_OUTPUT"
      - name: "Check pubspec version matches tag"
        run: |
          if [[ $(grep -E "^version: ${{ steps.get_release_name.outputs.release_name }}\+[0-9]+$" pubspec.yaml) == "" ]]; then
            echo "Tag does not match pubspec version"
            exit 1
          fi
  build-android:
    name: "Build Android"
    runs-on: ubuntu-latest
    needs: check_release
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Install flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.19.5"
          cache: true
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Build App"
        run: flutter build apk --release --no-tree-shake-icons
      - name: "Create artifact"
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
  build-ios:
    name: "Build IOS"
    runs-on: macos-latest
    needs: check_release
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Install flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.16.0"
          cache: true
          architecture: "x64"
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Build App"
        run: flutter build ios --release --no-codesign
      - name: "Create artifact"
        uses: actions/upload-artifact@v3
        with:
          name: Runner.app
          path: build/ios/iphoneos/Runner.app
  create_release:
    name: "Create Release"
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
      - name: "Download Android artifact"
        uses: actions/download-artifact@v3
        with:
          name: app-release.apk
      - name: "Download IOS artifact"
        uses: actions/download-artifact@v3
        with:
          name: Runner.app
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Runner
            app-release.apk
